# this file as config struct
[orm]
    dsn = "root:1234@tcp(192.168.31.51:3307)/gbbmn?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"
    debug = true

[db]
    addr = "192.168.31.51:3307"
    dsn = "root:1234@tcp(192.168.31.51:3307)/gbbmn?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 10
    idle = 5
    idleTimeout ="4h"
    queryTimeout = "12500ms"
    execTimeout = "12500ms"
    tranTimeout = "12500ms"
    [db.breaker]
        window = "5s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.4
        request = 100

[redis]
    proto = "tcp"
    addr = "192.168.31.51:6379"
    auth = "1234"
    active = 100
    idle = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    expire = "10s"

[minio]
    endpoint = "192.168.31.51:2234"
    accessKeyID = "coint"
    secretAccessKey = "123456789"
    useSSL = false

[http]
    host = "0.0.0.0"
    port = 50052
    ReadTimeout = 60
    WriteTimeout = 60
    MaxHeaderBytes = 102400

[httpClient]
    dial = "2s"
    timeout = "100s"
    keepAlive = "60s"
    timer = 1000
    [httpClient.breaker]
    window  = "10s"
    sleep   = "2000ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[log]
    logger_file = "logs/log.log"

[mqtt]
    url = "tcp://192.168.31.51:1883"
    debug = true
